* icons in errors

diff --git a/host/tarball/share/myx.common/bin/lib/installEnsurePackage b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
--- a/host/tarball/share/myx.common/bin/lib/installEnsurePackage
+++ b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
@@ -16,10 +16,10 @@ InstallEnsurePackage(){
 	UserRequireRoot "InstallEnsurePackage"
 	which -s brew || myx.common install/brew
 
-	[ -z "$SUDO_USER" ] && echo "ERROR: InstallEnsurePackage: The SUDO_USER env variable is required!" >&2 && return 1
+	[ -z "$SUDO_USER" ] && echo "⛔ ERROR: InstallEnsurePackage: The SUDO_USER env variable is required!" >&2 && return 1
 
 	local NAME="$1"
-	[ -z "$NAME" ] && echo "ERROR: The utility name is required!" >&2 && return 1
+	[ -z "$NAME" ] && echo "⛔ ERROR: The utility name is required!" >&2 && return 1
 
 	local LIST=""
 
