* install/ensure - reorganised

diff --git a/host/tarball/share/myx.common/bin/lib/installEnsurePackage b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
--- a/host/tarball/share/myx.common/bin/lib/installEnsurePackage
+++ b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
@@ -3,31 +3,35 @@
 type UserRequireRoot >/dev/null 2>&1 || \
 	. "/usr/local/share/myx.common/bin/user/requireRoot"
 
+InstallEnsurePackageTransformPackageName(){
+		case "$1" in
+		        go)
+		        	echo "golang" ; return 0 ;;
+		        java)
+		        	echo "openjdk" ; return 0 ;;
+				*)
+					echo "$1" ; return 0 ;;
+		esac
+}
+
 InstallEnsurePackage(){
 	# not on mac/brew: UserRequireRoot "InstallEnsurePackage"
-
 	which -s brew || myx.common install/brew
-	
-	local UTILITY_NAME="$1"
-	[ -z "$UTILITY_NAME" ] && echo "The utility name is required!" && exit 1
 
-	local PACKAGE_NAME="${2:-$UTILITY_NAME}"
-	
-	if [ ! -z "`which $UTILITY_NAME`" ] ; then \
-		echo "Utility is present: $UTILITY_NAME, skip" >&2
-	 else \
-		case "$PACKAGE_NAME" in
-		        go)
-		        	PACKAGE_NAME="golang"
-		        	break
-					;;
-		        java)
-					PACKAGE_NAME="openjdk"
-		        	break
-					;;
-		esac
-		brew install $PACKAGE_NAME
-	fi
+	local NAME="$1"
+	[ -z "$NAME" ] && echo "The utility name is required!" && exit 1
+
+	local LIST=""
+
+	for NAME in $@ ; do
+		which -s $NAME \
+			&& echo "ensure: $NAME already present, skip" >&2 \
+			|| LIST="$LIST `InstallEnsurePackageTransformPackageName $NAME`"
+	done
+
+	[ -z "$LIST" ] \
+		&& echo "all packages installed." >&2 \
+		|| brew install $LIST
 }
 
 case "$0" in
