* TryFetchStdout

diff --git a/host/tarball/share/myx.common/bin/install/updates b/host/tarball/share/myx.common/bin/install/updates
--- a/host/tarball/share/myx.common/bin/install/updates
+++ b/host/tarball/share/myx.common/bin/install/updates
@@ -6,9 +6,13 @@
 
 TryFetchStdout(){
 	local URL="$1"
-	[ ! -z "$URL" ] || (echo "TryFetchStdout: The URL is required!" ; return 0)
-	if [ ! -z "`which curl || true`" ]  ; then curl --silent -L "$URL"  ; return 0 ; fi
-	if [ ! -z "`which wget || true`" ]  ; then wget --quiet -O - "$URL" ; return 0 ; fi
+	[ -n "$URL" ] || (echo "TryFetchStdout: The URL is required!" ; return 0)
+    command -v curl  >/dev/null 2>&1 && { curl --silent -L "$URL"; return 0; }
+    command -v fetch >/dev/null 2>&1 && { fetch -o - "$URL"; return 0; }
+    command -v wget  >/dev/null 2>&1 && { wget --quiet -O - "$URL"; return 0; }
+	
+	echo "⛔ ERROR: curl, fetch, or wget were not found, do not know how to download!" >&2
+    exit 1
 }
 
 InstallUpdates(){
